IVDEPTH = ../../..
include $(IVDEPTH)/makeincs/ivcommondefs

CXXFILES = \
	SoXtUIRegion.c++ \
	SoXtColEd.c++ \
	SoXtColPatch.c++ \
	SoXtColSlider.c++ \
	SoXtColWheel.c++ \
	SoXtSlider.c++ \
	SoFloatCBList.c++

all install: $(OBJECTS) 

include $(IVCOMMONRULES)
