IVDEPTH = ../../../../..
include $(IVDEPTH)/makeincs/ivcommondefs

HDRSUBDIR = actions

HEADERS = \
	SoBoxHighlightRenderAction.h \
	SoLineHighlightRenderAction.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
