IVDEPTH = ../../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = eventTest

CXXFILES = \
	ButtonBoxEvent.c++ DialEvent.c++ \
	DialNButton.c++ eventTest.c++

LLDLIBS = -lInventor -lInventorXt -lXm -lXt -lX11 -lGLU -lGL -lXi

all: all_ivbin

include $(IVCOMMONRULES)
