IVDEPTH = ../../../../../../..
include $(IVDEPTH)/makeincs/ivcommondefs

LCXXINCS += -I../head
LCXXDEFS += -DLIBRARYBUILD

CXXFILES = nurbsClient.c++

all install: $(OBJECTS)

include $(IVCOMMONRULES)
