IVDEPTH = ../../../../..
include $(IVDEPTH)/makeincs/ivcommondefs

HDRSUBDIR = Xt/devices

HEADERS = \
	SoXtDevice.h \
	SoXtInputFocus.h \
	SoXtKeyboard.h \
	SoXtMouse.h \
	SoXtSpaceball.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
