IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = linkages

CXXFILES = linkages.c++ LinkClasses.c++ LinkEngines.c++

LLDLIBS = -lInventor -lInventorXt -lXm -lXt

all: all_ivbin

include $(IVCOMMONRULES)
