IVDEPTH = ../../../../..
include $(IVDEPTH)/makeincs/ivcommondefs

HDRSUBDIR = caches

HEADERS = \
	SoBoundingBoxCache.h \
	SoCache.h \
	SoGLCacheList.h \
	SoGLRenderCache.h \
	SoNormalCache.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
