IVDEPTH = ../../../..
include $(IVDEPTH)/makeincs/ivcommondefs

PROGRAM = jumpingJackKitTest

CXXFILES = JumpingJackKit.c++ jumpingJackKitTest.c++

LLDLIBS = -lInventor -lInventorXt -lXm -lXt -lX11 -lGLU -lGL

all: all_ivbin

include $(IVCOMMONRULES)
