IVDEPTH = ../../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = pyramidKitTest

CXXFILES = PyramidKit.c++ pyramidKitTest.c++

LLDLIBS = ../02.Nodes/Pyramid.o  -lInventor -lInventorXt -lXm -lXt -lX11 -lGLU -lGL

all: all_ivbin

include $(IVCOMMONRULES)
