IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = ivNodeKitStructure

CXXFILES = ivNodeKitStructure.c++

LLDLIBS = -lInventor -lInventorXt -ldl

all: all_ivbin

include $(IVCOMMONRULES)
