IVDEPTH = ../../../../..
include $(IVDEPTH)/makeincs/ivcommondefs

HDRSUBDIR = nodes

HEADERS = SoAntiSquish.h SoSelection.h SoSurroundScale.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
