const char gviewIcons[] =
"#Inventor V2.0 ascii\n"
"\n"
"Separator {\n"
"\n"
"    # Define main group geometry\n"
"    Switch {\n"
"	DEF groupGeom+0 Separator {\n"
"	    Material {\n"
"		diffuseColor	0.3 0.3 0.9\n"
"		specularColor	0.7 0.7 0.7\n"
"		shininess	0.2\n"
"	    }\n"
"	    DEF nodeGeom+1 Separator {\n"
"		Complexity {\n"
"		    value	0.3\n"
"		}\n"
"		Sphere {\n"
"		}\n"
"	    }\n"
"	}\n"
"	DEF plainNode+2 Separator {\n"
"	    Material {\n"
"		diffuseColor	0.6 0.3 0.3\n"
"		specularColor	0.5 0.5 0.5\n"
"		shininess	0.2\n"
"	    }\n"
"	    USE nodeGeom+1\n"
"	}\n"
"	DEF arrow+3 Separator {\n"
"	    Cylinder {\n"
"		radius	0.1\n"
"		height	1.5\n"
"	    }\n"
"	    Translation {\n"
"		translation	0 1 0\n"
"	    }\n"
"	    Cone {\n"
"		bottomRadius	0.3\n"
"		height	0.5\n"
"	    }\n"
"	}\n"
"	DEF standOutMaterial+4 Material {\n"
"	    ambientColor	0 0 0\n"
"	    diffuseColor	0 0 0\n"
"	    emissiveColor	0.9 0 0\n"
"	}\n"
"    }\n"
"    Separator {\n"
"	Label {\n"
"	    label	\"Instance\"\n"
"	}\n"
"	BaseColor {\n"
"	    rgb	0.5 0.5 0.1\n"
"	}\n"
"	Separator {\n"
"	    Cube {\n"
"		width	0.6\n"
"		height	1.2\n"
"	    }\n"
"	}\n"
"	Separator {\n"
"	    Translation {\n"
"		translation	0 0.8 0\n"
"	    }\n"
"	    DEF instanceBar+5 Cube {\n"
"		width	1.2\n"
"		height	0.4\n"
"	    }\n"
"	}\n"
"	Separator {\n"
"	    Translation {\n"
"		translation	0 -0.8 0\n"
"	    }\n"
"	    USE instanceBar+5\n"
"	}\n"
"    }\n"
"    Separator {\n"
"	Label {\n"
"	    label	\"Closed\"\n"
"	}\n"
"	Scale {\n"
"	    scaleFactor	0.75 0.75 0.75\n"
"	}\n"
"	USE groupGeom+0\n"
"	Separator {\n"
"	    Transform {\n"
"		translation	0 -1.3 0\n"
"		scaleFactor	1 0.5 1\n"
"	    }\n"
"	    BaseColor {\n"
"		rgb	0.6 0.4 0.3\n"
"	    }\n"
"	    Cone {\n"
"	    }\n"
"	}\n"
"    }\n"
"    Separator {\n"
"	Label {\n"
"	    label	\"Node\"\n"
"	}\n"
"	USE plainNode+2\n"
"    }\n"
"    Separator {\n"
"	Label {\n"
"	    label	\"Group\"\n"
"	}\n"
"	USE groupGeom+0\n"
"    }\n"
"    Separator {\n"
"	Label {\n"
"	    label	\"Separator\"\n"
"	}\n"
"	USE groupGeom+0\n"
"	Separator {\n"
"	    Material {\n"
"		ambientColor	0 0 0\n"
"		diffuseColor	0 0 0\n"
"	    }\n"
"	    Cube {\n"
"		height	0.3\n"
"	    }\n"
"	}\n"
"    }\n"
"    Separator {\n"
"	Label {\n"
"	    label	\"Switch\"\n"
"	}\n"
"	USE groupGeom+0\n"
"	Separator {\n"
"	    Transform {\n"
"		translation	0 0 1\n"
"		rotation	0 0 1  2.7\n"
"		scaleFactor	0.7 0.7 0.7\n"
"	    }\n"
"	    USE standOutMaterial+4\n"
"	    USE arrow+3\n"
"	}\n"
"    }\n"
"    Separator {\n"
"	Label {\n"
"	    label	\"Shape\"\n"
"	}\n"
"	Separator {\n"
"	    Material {\n"
"		diffuseColor	0.3 0.7 0.3\n"
"		specularColor	0.5 0.5 0.5\n"
"		shininess	0.2\n"
"	    }\n"
"	    USE nodeGeom+1\n"
"	}\n"
"	Separator {\n"
"	    USE standOutMaterial+4\n"
"	    Translation {\n"
"		translation	0 0 0.9\n"
"	    }\n"
"	    Cube {\n"
"		width	0.8\n"
"		height	0.8\n"
"		depth	0.2\n"
"	    }\n"
"	}\n"
"    }\n"
"    Separator {\n"
"	Label {\n"
"	    label	\"Transformation\"\n"
"	}\n"
"	USE plainNode+2\n"
"	Separator {\n"
"	    USE standOutMaterial+4\n"
"	    Separator {\n"
"		Transform {\n"
"		    translation	0.35 0.05 1\n"
"		    rotation	0 0 1  2.356\n"
"		}\n"
"		DEF transformArrow+6 Separator {\n"
"		    Scale {\n"
"			scaleFactor	0.9 0.4 0.9\n"
"		    }\n"
"		    USE arrow+3\n"
"		}\n"
"	    }\n"
"	    Separator {\n"
"		Transform {\n"
"		    translation	-0.35 -0.05 1\n"
"		    rotation	0 0 -1  0.785\n"
"		}\n"
"		USE transformArrow+6\n"
"	    }\n"
"	}\n"
"    }\n"
"    Separator {\n"
"	Label {\n"
"	    label	\"BaseColor\"\n"
"	}\n"
"	Label {\n"
"	    label	\"DrawStyle\"\n"
"	}\n"
"	Label {\n"
"	    label	\"Environment\"\n"
"	}\n"
"	Label {\n"
"	    label	\"Font\"\n"
"	}\n"
"	Label {\n"
"	    label	\"LightModel\"\n"
"	}\n"
"	Label {\n"
"	    label	\"Material\"\n"
"	}\n"
"	Label {\n"
"	    label	\"MaterialBinding\"\n"
"	}\n"
"	Label {\n"
"	    label	\"PackedColor\"\n"
"	}\n"
"	Label {\n"
"	    label	\"Texture2\"\n"
"	}\n"
"	Label {\n"
"	    label	\"Texture2Transform\"\n"
"	}\n"
"	Label {\n"
"	    label	\"TextureCoordinateBinding\"\n"
"	}\n"
"	Label {\n"
"	    label	\"TextureCoordinateFunction\"\n"
"	}\n"
"	USE plainNode+2\n"
"	Separator {\n"
"	    USE standOutMaterial+4\n"
"	    Transform {\n"
"		rotation	1 0 0  0.2\n"
"	    }\n"
"	    Cylinder {\n"
"		radius	1.02\n"
"		height	0.3\n"
"	    }\n"
"	}\n"
"    }\n"
"    Separator {\n"
"	Label {\n"
"	    label	\"Complexity\"\n"
"	}\n"
"	Label {\n"
"	    label	\"Coordinate3\"\n"
"	}\n"
"	Label {\n"
"	    label	\"Coordinate4\"\n"
"	}\n"
"	Label {\n"
"	    label	\"Normal\"\n"
"	}\n"
"	Label {\n"
"	    label	\"NormalBinding\"\n"
"	}\n"
"	Label {\n"
"	    label	\"Profile\"\n"
"	}\n"
"	Label {\n"
"	    label	\"ProfileCoordinate2\"\n"
"	}\n"
"	Label {\n"
"	    label	\"ProfileCoordinate3\"\n"
"	}\n"
"	Label {\n"
"	    label	\"ShapeHints\"\n"
"	}\n"
"	USE plainNode+2\n"
"	Separator {\n"
"	    USE standOutMaterial+4\n"
"	    Coordinate3 {\n"
"		point	[ -0.5 0.5 1,\n"
"				  0 0.5 1,\n"
"				  0.5 0.5 1,\n"
"				  -0.5 0 1,\n"
"				  0 0 1,\n"
"				  0.5 0 1,\n"
"				  -0.5 -0.5 1,\n"
"				  0 -0.5 1,\n"
"				  0.5 -0.5 1 ]\n"
"	    }\n"
"	    DrawStyle {\n"
"		style	LINES\n"
"	    }\n"
"	    QuadMesh {\n"
"		verticesPerColumn	3\n"
"		verticesPerRow	3\n"
"	    }\n"
"	}\n"
"    }\n"
"}\n"
;
