IVDEPTH = ../../../../..
include $(IVDEPTH)/makeincs/ivcommondefs

CXXFILES = \
	SoField.c++ \
	SoFieldContainer.c++ \
	SoFieldData.c++ \
	SoFieldInit.c++ \
	SoFields.c++ \
	SoGlobalField.c++

all install: $(OBJECTS)

include $(IVCOMMONRULES)
