IVDEPTH = ../../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = viewer

CXXFILES = viewer.c++ simpleViewer.c++

LLDLIBS =  -lInventor -lInventorXt -lXm -lXt -lX11 -lGLU -lGL

all: all_ivbin

include $(IVCOMMONRULES)
