IVDEPTH = ../../../..
include $(IVDEPTH)/makeincs/ivcommondefs

PROGRAM = tumble

CXXFILES = tumble.c++ SceneTumble.c++

LLDLIBS = -lInventor -lInventorXt -lXm -lXt -lX11 -lGLU -lGL

all: all_ivbin

include $(IVCOMMONRULES)
