IVDEPTH = ../../..
include $(IVDEPTH)/makeincs/ivcommondefs

PROGRAM = 4view

CXXFILES = 4view.c++

LLDLIBS = -lInventor -lInventorXt -lXm -lXt

all: all_ivbin

install: install_ivsamples

include $(IVCOMMONRULES)
