IVDEPTH = ../../../..
include $(IVDEPTH)/makeincs/ivcommondefs

PROGRAM = newNodes

CXXFILES = newNodes.c++ Glow.c++ Pyramid.c++ Alternate.c++

LLDLIBS = -lInventor -lInventorXt -lXm -lXt -lX11 -lGLU -lGL

all: all_ivbin

include $(IVCOMMONRULES)
