IVDEPTH = ../../..
include $(IVDEPTH)/makeincs/ivcommondefs

DSO = BarChart.so

CXXFILES = BarChart.c++

LLDLIBS = -L$(IVDEPTH)/libInventor -lInventor -L$(IVDEPTH)/libSoXt -lInventorXt

all install: all_ivbin

include $(IVCOMMONRULES)
